# This is a basic workflow to help you get started with Actions

name: npm-publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: ['14']
    name: Node ${{ matrix.node }} sample
    steps:
      - name: Cit Clone project
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install

      - name: Testing and Build project
        run: |
          npm test
          npm start

      - name: List current folder
      - run: ls -la

      - name: Publish to NPM
        uses: ./
        with:
          token: ${{ secrets.NPM_TOKEN }}
