# This is a basic workflow to help you get started with Actions

name: npm-publish

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1

      - name: Publish to NPM
        uses: ./
        with:
          token: ${{ secrets.NPM_TOKEN }}
