# This is a basic workflow to help you get started with Actions

name: npm-publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - run: npm test
